"""empty message

Revision ID: 9454ef0b3871
Revises: 
Create Date: 2022-06-03 15:49:25.828687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9454ef0b3871'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adv_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adv_model_description'), 'adv_model', ['description'], unique=True)
    op.create_index(op.f('ix_adv_model_header'), 'adv_model', ['header'], unique=True)
    op.create_index(op.f('ix_adv_model_owner'), 'adv_model', ['owner'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adv_model_owner'), table_name='adv_model')
    op.drop_index(op.f('ix_adv_model_header'), table_name='adv_model')
    op.drop_index(op.f('ix_adv_model_description'), table_name='adv_model')
    op.drop_table('adv_model')
    # ### end Alembic commands ###
